### ISSUE TITLE
Implement Command box and help bar UI

### ISSUE THREAD

**Issue by optionalemon** [AY2223S1-CS2103T-T12-1/tp#193]
- [x] Shift command box to the bottom
- [x] Delete 'File'
- [x] Shift help bar to the right and make sure it redirects upon clicking
- [x] Match colour and theme
