### ISSUE TITLE
Implement Focus Screen UI

### ISSUE THREAD

**Issue by optionalemon** [AY2223S1-CS2103T-T12-1/tp#194]
- [x] Create and display session and grade list
- [x] Modify button bar with a backward arrow
- [x] Match colour and theme
- [ ] Wrap up UI and update PPP, DG, UG and other relevant documentation
